
%=========================================================================
%
%   Program to generate realized random numbers from the
%       1. Time invariant model
%       2. Count model
%       3. Linear regression model
%       4. Exponential regression model
%       5. Autoregressive model
%       6. Bilinear model
%       7. Autoregressive and heteroskedastic model
%       8. ARCH model
%    
%   The realizations of the random draws from the models will be 
%   different to those reported in the text as the random numbers
%   generated by the Gauss random number generator differ from those 
%   generated by Matlab. Consequently the realizations are not printed
%   in this program and the PICTURE WILL BE DIFFERENT TO THE FIGURES
%   IN CHAPTER 1.
%
%=========================================================================

clear all;
clc;

% Set seed of random number generator
RandStream.setDefaultStream( RandStream('mt19937ar','seed',1234567) )

t = 5;       

% Time invariant model

mu  = 0;                            % Mean
sig = 2;                            % Standard deviation                           
z   = randn(t,1);                   % Standard normal random numbers     
y   = sig*z;                        % Generate realizations of y                      
s   = (-10:0.1:10)';                    
fz  = normpdf(s);                   % Probability distribution of z       
fy  = normpdf((s-mu)/sig)*(1/sig);  % Probability distribution of y                   
s1  = s;  
y1  = y; 
fz1 = fz;
fy1 = fy;

% Count model
theta   = 2;                                 
y       = poissrnd(theta,t,1);                                            
s       = 0:1:9;                          
s2      = s;
y2      = y;
fy2     = poisspdf(s,theta);

% Linear regression model
beta = 3;                                       
sig  = 2;
z    = randn(t,1);                              
x    = (0:1:t-1)';                              
y    = beta*x + sig*z;                          
s    = (-10:0.1:20)';                           
fz   = normpdf(s);                              
tmp0 = repmat(s,1,length(beta*x'));
tmp1 = repmat(beta*x',length(s),1);
fy   = normpdf( (tmp0-tmp1)./sig )*(1/sig);     
s3   = s;                                        
y3   = y;
fz3  = fz;
fy3  = fy;


% Exponential regression model
b0    = 1;                             
b1    = 2;
x     = (0:1:t-1)';                    
mu    = b0 + b1*x;
z    = rand(t,1);                     
y    = -mu.*log(1 - z);               
s    = (0.1:0.1:20)';                 
tmp0 = repmat( s,1,length(mu') );
tmp1 = repmat( mu',length(s),1 );
fy   = exp(-tmp0./tmp1)./tmp1;        
s4   = s;
y4   = y;
fy4  = fy;

% Autoregressive model
rho = 0.8;                                                             
sig = 2;
u   = sig*randn(t+1,1);                       

y0(1) = 0;
for i = 2:length(u+1)   
    y0(i) = rho*y0(i-1)+u(i-1);         	
end

y    = y0(2:end)';
yl   = y0(1:end-1)';                                                    
s    = (-10:0.1:10)';   
fu   = normpdf(s/sig)*(1/sig);              
tmp0 = repmat(s,1,length(rho*yl'));
tmp1 = repmat(rho*yl',length(s),1);
fu   = normpdf(s/sig)*(1/sig);              
tmp1 = repmat(rho*yl',length(s),1);
fy   = normpdf( (tmp0-tmp1)./sig )*(1/sig);
s5   = s;
y5   = y;
fu5  = fu;
fy5  = fy;


% Bilinear time series model
rho = 0.8;                                                            
gam = 0.4;
sig = 2;

u  = sig*randn(t,1);                         
mu = zeros(t,1);
y  = zeros(t,1);


for i=2:t
     mu(i) = rho*y(i-1) + gam*y(i-1)*u(i-1);
     y(i)  = mu(i) + u(i);
end

s  = (-10:0.1:10)';                      	

fu = normpdf(s/sig)*(1/sig);                               

tmp0 = repmat(s,1,length(mu'));
tmp1 = repmat(mu',length(s),1);
fy   = normpdf( (tmp0-tmp1)./sig )*(1/sig);  

s6 = s;
y6 = y;
fu6 = fu;
fy6 = fy;

% Autoregressive model with heteroskedasticity
rho = 0.8;                                                                
a0  = 0.8;
a1  = 0.8;

w    = rand(t+1,1);                             
sig2 = a0 + a1*w;                                                   
sig  = sqrt(sig2);                              

u = sig.*rand(t+1,1);                           

y0(1) = 0.0;
for i = 2:length(u+1)   
    y0(i) = rho*y0(i-1)+u(i-1);                 
end

y   = y0(2:end)';
yl  = y0(1:end-1)';                                                        
sig = sig(2:end);

s  = (-10:0.1:10)';                                 

fz = normpdf(s);                                             

tmp0 = repmat(s,1,length(rho*yl'));
tmp1 = repmat(rho*yl',length(s),1);
tmp2 = repmat(sig',length(s),1);
fu   = normpdf(tmp0./tmp2).*(1./tmp2);           
fy   = normpdf( (tmp0-tmp1)./tmp2 ).*(1./tmp2); 

s7   = s;
y7   = y;
fz7  = fz;
fy7  = fy;


% ARCH model
beta   = 3.0;                                                 
alpha0 = 4.0;
alpha1 = 0.9;

z = randn(t+1,1);                            
x = (-1:1:t-1)';                           	            
y0 = zeros(t,1);
u = zeros(t+1,1);
sig2 = zeros(t+1,1) + alpha0;
sig = sqrt(sig2);

for i=2:t
	sig2(i) = alpha0 + alpha1*u(i-1)^2;
	sig(i)  = sqrt(sig2(i));
	u(i)    = sig(i)*z(i);
	y0(i)   = beta*x(i) + u(i);
end

y   = y0(2:end);
x   = x(2:end);
sig = sig(2:end);

s = (-10:0.1:20)';                      	     
fz = normpdf(s);                                           
tmp0 = repmat(s,1,length(beta*x'));
tmp1 = repmat(beta*x',length(s),1);
tmp2 = repmat(sig',length(s),1);
fy = normpdf((tmp0-tmp1)./tmp2 ).*(1./tmp2); 	                 

s8 = s;
y8 = y;
fz8 = fz;
fy8 = fy;

% Plot the data

figure(1);
clf;

%--------------------------------------------------------%
% Panel (a)
subplot(4,2,1)
plot(s1,fz1,'-k',...
     s1,fy1,'--k',...
    'LineWidth',0.75);
title('(a) Time Invariant Model');
ylabel('f(y)');
xlabel('y');
legend('z','y','Location','NorthEast')
legend('boxoff')

%--------------------------------------------------------%
% Panel (b)
subplot(4,2,2)
bar(s2,fy2);
title('(b) Count Model');
ylabel('f(y)');
xlabel('y');
axis([-0.5 9.5 0 0.35]) 
h = findobj(gca,'Type','patch');
set(h,'FaceColor','w','EdgeColor','k')


%--------------------------------------------------------%
% Panel (c)
subplot(4,2,3)
plot(s3,fy3(:,1),'-k',...
     s3,fy3(:,3),'--k',...
     s3,fy3(:,5),':k',...
    'LineWidth',0.75);
title('(c) Linear Regression Model');
ylabel('f(y)');
xlabel('y');
%legend('z','y1','y3','y5','Location','NorthEast')
%legend('boxoff')



%--------------------------------------------------------%
% Panel (d)
s4 = (0.1:0.1:20)';
subplot(4,2,4)
plot(s4,fy4(:,1),'-k',...
     s4,fy4(:,3),'--k',...
     s4,fy4(:,5),':k',...
    'LineWidth',0.75);
title('(d) Exponential Regression Model');
ylabel('f(y)');
xlabel('y');
%legend('y1','y3','y5','Location','NorthEast')
%legend('boxoff')
 
%legend2latex(f1)

%--------------------------------------------------------%
% Panel (e)
subplot(4,2,5)
plot(s5,fy5(:,1),'-k',...
     s5,fy5(:,3),'--k',...
     s5,fy5(:,5),':k',...
     'LineWidth',0.75);
title('(a) Autoregressive Model');
ylabel('f(y)');
xlabel('y');


%--------------------------------------------------------%
% Panel (f)
subplot(4,2,6)
plot(s6,fy6(:,1),'-k',...
     s6,fy6(:,3),'--k',...
     s6,fy6(:,5),':k',...
    'LineWidth',0.75);
title('(b) Bilinear Model');
ylabel('f(y)');
xlabel('y');


%--------------------------------------------------------%
% Panel (g)
subplot(4,2,7)
plot(s7,fy7(:,1),'-k',...
     s7,fy7(:,3),'--k',...
     s7,fy7(:,5),':k',...
    'LineWidth',0.75);
title('(c) Autoregressive Heteroskedastic Model');
ylabel('f(y)');
xlabel('y');
%legend('y1','y3','y5','Location','NorthEast')
%legend('boxoff')
% set(gca,'XTick',-10:5:20)
% set(gca,'YTick',0:0.05:0.5)
% xlim([-10,10])
ylim([0,0.5])

%--------------------------------------------------------%
% Panel (d)

subplot(4,2,8)
plot(s8,fy8(:,1),'-k',...
     s8,fy8(:,3),'--k',...
     s8,fy8(:,5),':k',...
    'LineWidth',0.75);
title('(d) ARCH Model');
ylabel('f(y)');
xlabel('y');
% set(gca,'XTick',-10:5:20)
% set(gca,'YTick',0:0.1:0.45)
% xlim([-10,20])
% ylim([0,0.45])





