
%=========================================================================
%
%   This program generates the graphs in Figures 1.1 and 1.2. Data are 
%   generated by the Gauss random number generator for consistency.
%
%=========================================================================

clear all;
clc;

% Load data
load sampledata.mat

t = 5;       % Sample size 
s = (-10:0.1:20)';


%***********************************************************************
%***
%***     Generate graphs
%***
%***********************************************************************

% Switch off TeX interpreter and clear figure
% First figure
set(0,'defaulttextinterpreter','none');
figure(1);
clf;

%--------------------------------------------------------%
% Panel (a)
s1 = (-10:0.1:10)';
subplot(2,2,1)
plot(s1,fz1,'-k',...
     s1,fy1,'--k',...
    'LineWidth',0.75);
title('(a) Time Invariant Model');
ylabel('$f(y)$');
xlabel('$y$');
legend('z','y','Location','NorthEast')
legend('boxoff')

%--------------------------------------------------------%
% Panel (b)
subplot(2,2,2)
bar(0:1:9,fycount);
title('(b) Count Model');
ylabel('$f(y)$');
xlabel('$y$');
axis([-0.5 9.5 0 0.35]) 
h = findobj(gca,'Type','patch');
set(h,'FaceColor','w','EdgeColor','k')

%legend('y1','y3','y5','Location','NorthEast')
%legend('boxoff')


%--------------------------------------------------------%
% Panel (c)
s3 = (-10:0.1:20)';
subplot(2,2,3)
plot(s3,fy3(:,1),'-k',...
     s3,fy3(:,3),'--k',...
     s3,fy3(:,5),':k',...
    'LineWidth',0.75);
title('(c) Linear Regression Model');
ylabel('$f(y)$');
xlabel('$y$');
%legend('z','y1','y3','y5','Location','NorthEast')
%legend('boxoff')



%--------------------------------------------------------%
% Panel (d)
s2 = (-10:0.1:20)';
subplot(2,2,4)
plot(s2,fy2(:,1),'-k',...
     s2,fy2(:,3),'--k',...
     s2,fy2(:,5),':k',...
    'LineWidth',0.75);
title('(d) Exponential Regression Model');
ylabel('$f(y)$');
xlabel('$y$');
%legend('y1','y3','y5','Location','NorthEast')
%legend('boxoff')
 
%legend2latex(f1)

% Print the tex file 
laprint(1,'sample1','options','factory');

% Second figure
figure(2);
clf;

%--------------------------------------------------------%
% Panel (a)
s5 = (-10:0.1:10)';
subplot(2,2,1)
plot(s5,fy5(:,1),'-k',...
     s5,fy5(:,3),'--k',...
     s5,fy5(:,5),':k',...
     'LineWidth',0.75);
title('(a) Autoregressive Model');
ylabel('$f(y)$');
xlabel('$y$');
%legend('y1','y3','y5','Location','NorthEast')
%legend('boxoff')


%--------------------------------------------------------%
% Panel (b)
s6 = (-10:0.1:20)';
subplot(2,2,2)
plot(s6,fy6(:,1),'-k',...
     s6,fy6(:,3),'--k',...
     s6,fy6(:,5),':k',...
    'LineWidth',0.75);
title('(b) Bilinear Model');
ylabel('$f(y)$');
xlabel('$y$');
%legend('y1','y3','y5','Location','NorthEast')
%legend('boxoff')


%--------------------------------------------------------%
% Panel (c)
s7 = (-10:0.1:10)';
subplot(2,2,3)
plot(s7,fy7(:,1),'-k',...
     s7,fy7(:,3),'--k',...
     s7,fy7(:,5),':k',...
    'LineWidth',0.75);
title('(c) Autoregressive Heteroskedastic Model');
ylabel('$f(y)$');
xlabel('$y$');
%legend('y1','y3','y5','Location','NorthEast')
%legend('boxoff')
% set(gca,'XTick',-10:5:20)
% set(gca,'YTick',0:0.05:0.5)
% xlim([-10,10])
ylim([0,0.5])

%--------------------------------------------------------%
% Panel (d)

subplot(2,2,4)
s8 = (-10:0.1:20)';
plot(s8,fy8(:,1),'-k',...
     s8,fy8(:,3),'--k',...
     s8,fy8(:,5),':k',...
    'LineWidth',0.75);
title('(d) ARCH Model');
ylabel('$f(y)$');
xlabel('$y$');
%legend('z','y1','y3','y5','Location','NorthEast')
%legend('boxoff')
% set(gca,'XTick',-10:5:20)
% set(gca,'YTick',0:0.1:0.45)
% xlim([-10,20])
% ylim([0,0.45])


% Print the tex file 
laprint(2,'sample2','options','factory');


