#
#===========================================================
#
#Program to generate realized random numbers from the
#       1. Time invariant model
#       2. Count model
#       3. Linear regression model
#       4. Exponential regression model
#       5. Autoregressive model
#       6. Bilinear model
#       7. Autoregressive and heteroskedastic model
#       8. ARCH model
#
#   The realizations of the random draws from the models will be
#   different to those reported in the text as the random numbers
#   generated by the Gauss random number generator differ from those
#   generated by Matlab. Consequently the realizations are not printed
#   in this program and the PICTURE WILL BE DIFFERENT TO THE FIGURES
#   IN CHAPTER 1.
#
#
#==============================================================

import numpy as np
import scipy.stats as stats


